// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsAEmNUu9DRp-KXDJHTKa_dIAyMl49X9g',
    appId: '1:972239047465:web:314094605e1eeee0a7c538',
    messagingSenderId: '972239047465',
    projectId: 'etracker-96a91',
    authDomain: 'etracker-96a91.firebaseapp.com',
    storageBucket: 'etracker-96a91.appspot.com',
    measurementId: 'G-N3Q7B8M71Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtEMTPheDdXRZUARhnCQ2TO8k8_odE6iw',
    appId: '1:972239047465:android:52f9dff7e4858463a7c538',
    messagingSenderId: '972239047465',
    projectId: 'etracker-96a91',
    storageBucket: 'etracker-96a91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZNmR3hQIUe-bPGHhlGk7DViP1H0unSQA',
    appId: '1:972239047465:ios:49b86019c30703eda7c538',
    messagingSenderId: '972239047465',
    projectId: 'etracker-96a91',
    storageBucket: 'etracker-96a91.appspot.com',
    iosBundleId: 'com.example.expensesTrackerProjectStage1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZNmR3hQIUe-bPGHhlGk7DViP1H0unSQA',
    appId: '1:972239047465:ios:53c8e1e6e9f04fa1a7c538',
    messagingSenderId: '972239047465',
    projectId: 'etracker-96a91',
    storageBucket: 'etracker-96a91.appspot.com',
    iosBundleId: 'com.example.expensesTrackerProjectStage1.RunnerTests',
  );
}
